- name: install docker
  apt: 
  
    name: "{{ item }}"
    state: present
    update_cache: yes

  loop:
    - docker.io
- name: Start services
  service:
    name: docker
    state: started
- name: Add user to docker group
  user:
    name: ubuntu
    group: docker
    append: yes
